name: Workflow for testing SPM archiving
on: 
  workflow_dispatch:
jobs:
  archiving:
    name: Archiving frameworks
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create xcframework
        uses: bsneed/swift-create-xcframework@bsneed/xcode15_fix