name: Workflow for testing SPM archiving
on: 
  workflow_dispatch:
jobs:
  archiving:
    name: Archiving frameworks
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Swift 5.9
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Create xcframework
        uses: bsneed/swift-create-xcframework@bsneed/xcode15_fix