name: Workflow for testing SPM archiving
on: 
  workflow_dispatch:
jobs:
  archiving:
    name: Archiving frameworks
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Swift 5.9
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_15.2.app" # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        env:
          destination: 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2'
      - name: Create xcframework
        uses: bsneed/swift-create-xcframework@bsneed/xcode15_fix