name: Workflow for testing SPM archiving
on: 
  workflow_dispatch:
jobs:
  archiving:
    name: Archiving frameworks
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: swift --version
      - name: Create xcframework
        uses: unsignedapps/swift-create-xcframework@v2
        with:
          xcconfig: Config.xcconfig